name: 'Create or update a Check Run'
description: 'Mirrors a workflow run to a Check Run of a Pull Request in a different repository'
author: 'Johannes Schindelin'
inputs:
  config:
    description: 'The GitGitGadget configuration to use (see https://github.com/gitgitgadget/gitgitgadget/blob/HEAD/lib/project-config.ts)'
    default: '' # sadly, ${{ vars.CONFIG }} does not work, and documentation about what contexts are permissible here is sorely missing
  pr-repo-token:
    description: 'The access token to work on the repository that holds PRs and state'
    required: true
  upstream-repo-token:
    description: 'The access token to work on PRs in the upstream repository'
    required: false
  test-repo-token:
    description: 'The access token to work on PRs in the test repository'
    required: false
  pr-url:
    description: 'The URL of the Pull Request (or Pull Request comment)'
    required: false
  check-run-id:
    description: 'The Check Run to update (if empty, a new one will be created)'
    default: ''
  name:
    description: 'The name of the CheckRun (required if check-run-id is empty)'
    default: ''
  title:
    description: 'The Check Run title (required when creating a new one)'
    default: ''
  summary:
    description: 'The Check Run summary (required when creating a new one)'
    default: ''
  text:
    description: 'The Check Run text (required when creating a new one)'
    default: ''
  details-url:
    description: 'The details URL of the Check Run (required when creating a new one)'
    default: ''
  conclusion:
    description: 'If set, the Check Run will be marked as completed'
    default: ''
outputs:
  check-run-id:
    description: 'The ID of the created or updated Check Run'
runs:
  using: 'node20'
  main: './index.js'
branding:
  icon: 'git-commit'
  color: 'orange'